version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  # output will be in /.src/{YOUR_PROJECT_DIR}/bin/Debug/netcoreapp2.1/publish/
  - cmd: dotnet publish ./user-webapi/user-webapi.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\user-webapi\bin\Debug\netcoreapp2.1\publish\'
   name: user-webapi
   type: WebDeployPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./user-webapitests/user-webapitests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: dotnet build user-webapitests/user-webapitests.csproj
  - cmd: cd user-webapitests\bin\Debug\netcoreapp2.1
  #GetUsers
  - cmd: dotnet vstest ./user-webapitests.dll /Tests:userwebapitests.UserControllerUnitTest.Task_GetUsers_Return_Ok --logger:trx
  # - cmd: dotnet vstest ./user-webapitests.dll /Tests:userwebapitests.UserControllerUnitTest.Task_GetUsers_Return_BadRequestResult --logger:trx
  # #GetUser
  # - cmd: dotnet vstest ./user-webapitests.dll /Tests:userwebapitests.UserControllerUnitTest.Task_GetUserById_Return_NotFound --logger:trx
  # - cmd: dotnet vstest ./user-webapitests.dll /Tests:userwebapitests.UserControllerUnitTest.Task_GetUserById_Return_BadRequestResult --logger:trx
  # - cmd: dotnet vstest ./user-webapitests.dll /Tests:userwebapitests.UserControllerUnitTest.Task_GetUserById_MatchResult --logger:trx
  # #PostUser
  # - cmd: dotnet vstest ./user-webapitests.dll /Tests:userwebapitests.UserControllerUnitTest.Task_PostUser_Return_Ok --logger:trx
  # - cmd: dotnet vstest ./user-webapitests.dll /Tests:userwebapitests.UserControllerUnitTest.Task_PostUser_Return_BadRequestResult --logger:trx
  # #PutUser
  # - cmd: dotnet vstest ./user-webapitests.dll /Tests:userwebapitests.UserControllerUnitTest.Task_PutUser_Return_MatchData --logger:trx
  # - cmd: dotnet vstest ./user-webapitests.dll /Tests:userwebapitests.UserControllerUnitTest.Task_PutUser_Return_OkResult --logger:trx
  # #DeleteUser
  # - cmd: dotnet vstest ./user-webapitests.dll /Tests:userwebapitests.UserControllerUnitTest.Task_Delete_User_Return_OkResult --logger:trx
  - cmd: move TestResults c:/projects/web-api-lab/user-webapi/bin/Debug/netcoreapp2.1/publish/
notifications:
  - provider: Email
    to:
      - ruirizzi@gmail.com
    subject: 'Build {{status}}'
    message: "{{message}}, {{commitId}}"

on_finish :
  # any cleanup in here
deploy: off
